# Project information
site_name: DFR Software Wiki
site_url: https://software.dallasformularacing.com/
site_author: Dallas Formula Racing
site_description: >-
  The home of anything and everything software related for Dallas Formula Racing.

# MkDocs build configuration
remote_branch: main
remote_name: origin

# Repository
repo_name: DallasFormulaRacing/software-wiki
repo_url: https://github.com/DallasFormulaRacing/software-wiki
edit_uri: edit/src/docs/

# Copyright
copyright: Copyright &copy; 2025 Dallas Formula Racing

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo.png

# CSS Changes
extra_css:
  - stylesheets/colors.css

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - open-in-new-tab

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DallasFormulaRacing

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true 

nav: 
  - index.md
  - Onboarding:
    - New to CS/SE: onboarding/new-to-CS-or-SE.md
    - Learning Python: onboarding/learning-Python.md
    - Learning Git: onboarding/learning-Git.md
    - Onboarding Project: onboarding/onboarding-project.md
  - Additional Resources:
    - Learning SQL: resources/learning-SQL.md
    - Learning Docker: resources/learning-Docker.md
  - Projects:
    - Cloud:
      - Assetto Corsa Streaming: projects/cloud/assetto-corsa-streaming.md
      - Star Stream: projects/cloud/star-stream.md
    - Deployment CI/CD:
      - CI/CD Overview: projects/deployment-ci-cd/deployment-platform.md
    - Frontend and Data Visualization:
      - Grafana Dashboard: projects/frontend-and-data-vis/grafana-dashboard.md
      - Web Dashboard: projects/frontend-and-data-vis/dashboard.md
    - Onboard Car:
      - Onboard CAN Streaming: projects/onboard-car/onboard-can-streaming.md
      - Racing Data Converter: projects/onboard-car/racing-data-converter.md
    - Finance Dashboard: projects/finance-dashboard.md
    - Software Wiki: projects/software-wiki.md
  - Policies:
    - Best Development Practices: policies/best-development-practices.md
    - Project Documentation Guidelines: policies/project-documentation-guidelines.md
    - Style Guide: policies/style-guide.md